rubocop:
  version: 0.68.0
  config_file: .rubocop.yml
scss:
  enabled: false
coffeescript:
  enabled: false
haml:
  config_file: .haml-lint.yml
javascript:
  enabled: false
scss:
  enabled: false
haml:
  enabled: false
