sudo: false
language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - jruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
notifications:
  flowdock:
    secure: fSZxX5z3bHWT8aCFKBFrDDt5o3Jb6EFWcm+pAcMabpfDHc4iktWuCUlSM405798TRdKdws1A2RncQGYiQyLbqNvtLz48dvj4BxgYW7P/vg0koN+I/H2MjpZeuIQ7BRSEJIq2sAYNVya+hSil+SPEBMTngJiP6VYG0dm6fFnRkyk=
